[tool.black]
line-length = 127
include = '\.pyi?$'
exclude = '''
(
    ^/env
    | \.mypy_cache
    | \.git
    | \.mypy_cache
)
'''
[tool.isort]
skip = [".gitignore", ".dockerignore", "env", ".mypy_cache","reports"]

[tool.mypy]
ignore_missing_imports = true
exclude = [
    '^api_app/src/main\.py$',

]