version: '3.0'

services:
  database:
    image: postgres:13-alpine3.16
    restart: always
    container_name: postgres_movies
    ports:
      - 5432:5432
    env_file:
      - postgres/.env
    volumes:
      - ./postgres/init_data_prod/:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data/
