name: Python application

on:
  push:
    branches: [ feature/cicd ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy flake8 black isort



      - name: isort
        run: isort --check .

      - name: flake8
        run: flake8 --config=setup.cfg

      - name: mypy_api_app
        run: mypy api_app

      - name: mypy_etl
        run: mypy etl
